### PR TITLE
Added icon to window

### PR DESCRIPTION
**Pull request by hashamyounis9**
Added icon to the window which displays in the window title bar and in the taskbar as well.

### CODE REVIEW

**Comment by hashamyounis9** [comment]
Hey @mominaamjad !

Recently I saw your project **scientific-calculator** on GitHub and made a little contribution to it by adding an Icon to the application hoping for you to merge the PR after reviewing it. Looking forward to positive response from you...

Here is the icon png: 
icon

**Comment by mominaamjad** [comment]
Hey @hashamyounis9, I checked out your request and the icon looks great. Thank you for contributing!

**Comment by hashamyounis9** [comment]
Thanks @mominaamjad for merging!

**Comment by hashamyounis9** [comment]
It would be better if you update images directory with images of the icon in app title bar and task bar and also add these screenshots to readme file

**Pull request merged**
